---
- name: Provisioning EC2 instances using Ansible
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  vars_files:
    - ./variables.yml

  tasks:
    - name: Create my security group
      local_action:
        module: ec2_group
        name: ansible
        description: Security Group for ansible Servers
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Create instance with public IP address
      amazon.aws.ec2_instance:
        name: "target"
        key_name: "dynamic"
        region: ap-south-1
        instance_type: t2.micro
        security_group: default
        count: 1
        network:
          assign_public_ip: true
        image_id: ami-0f5ee92e2d63afc18
        tags:
          Environment: ansible_node

    - name: Get system information
      shell:
        cmd: |
          hostname -I
          hostname
          cat /etc/*-release | grep VERSION_ID
      register: system_info

    - name: Display information
      debug:
        msg: "IP: {{ system_info.stdout_lines[0] }}, Hostname: {{ system_info.stdout_lines[1] }}, Version: {{ system_info.stdout_lines[2] }}"
